@startuml

/'
interface 飲み会Rep{
ID発行()
登録する(飲み会)
}

Interface 参加者Rep{
追加する(参加者)
参照する(飲み会ID):List<参加者>
削除する(参加者)
}
'/

class 幹事{
}

class 飲み会 {
飲み会ID
名前
開催日時
幹事
設定()
}


class 参加者{
名前
飲み会
支払区分
追加する()
削除する()
}

class 参加者一覧{
}


enum 支払区分{
多め
普通
少なめ
}

class 支払割合{
}

class 請求金額{
}

class 支払金額{
}

class 支払金額一覧{
}

class 支払金額計算policy{
}


飲み会 -> 幹事
参加者一覧 -> 飲み会
参加者一覧 -> 参加者
参加者 -> 支払区分
支払区分 -> 飲み会
支払区分 -> 支払割合
請求金額 -> 飲み会
支払金額一覧 -> 支払金額
支払金額一覧 -> 参加者一覧

支払金額計算policy -> 支払金額一覧
支払金額計算policy -> 請求金額
支払金額計算policy -> 参加者

@enduml
