@startuml

/'
class 幹事{
}
'/

class 飲み会 {
名前
開催日時
参会者一覧
支払区分
'幹事
開催(名前,開催日時,参加者一覧,請求金額)
'参加者追加()
金額計算(
:支払金額一覧
}


class 参加者{
名前
飲み会
支払区分
追加する()
}

class 参加者一覧{
List<参加者>
追加する()
}


enum 支払区分{
多め
普通
少なめ
}

class 支払割合{
}

class 請求金額{
}

class 支払金額{
参加者
}

class 支払金額一覧{
}

class 金額{
}



'飲み会 -> 幹事
飲み会 -> 参加者一覧
参加者一覧 -> 参加者
参加者 -> 支払区分
飲み会 -> 支払区分
飲み会 -> 支払金額一覧
支払区分 -> 支払割合
飲み会 -> 請求金額
支払金額一覧 -> 支払金額
支払金額 -> 参加者
支払金額 -> 金額

@enduml
