@startuml

/'
class 幹事{
}
'/

class 飲み会 {
名前
開催日時
参会者一覧
支払区分
'幹事
開催(名前,開催日時,参加者一覧,請求金額)
'参加者追加()
金額計算():支払金額一覧
}


class 参加者{
名前
'飲み会
支払区分
支払重みを教える()
}

class 参加者一覧{
List<参加者>
重み合計値を教える()
}


enum 支払区分{
多め
普通
少なめ
}

class 支払重み{
}

class 支払重み合計値{
}

class 請求金額{
}

class 支払一覧{
List<支払>
作成(参加者一覧,請求金額):支払一覧
private 重み毎支払金額を計算(参加者一覧)
}

class 支払{
参加者
参加者毎支払金額
作成(参加者,重み毎支払金額):支払
private 参加者毎支払金額を計算()

}


class 参加者毎支払金額{
}

/'
class メンバー毎支払割合{
参加者
支払割合
}
'/


class 金額{
}


/'
class 支払計算{
参加者一覧
請求金額
計算():支払金額一覧
private 重み毎支払金額を計算(参加者一覧)
private 参加者毎支配金額を計算()
}
'/


'飲み会 -> 幹事
飲み会  -d-> 参加者一覧
飲み会 -d-> 請求金額
'飲み会 -> 支払区分
'飲み会 -> 支払金額
飲み会 -d-> 支払一覧

参加者一覧 -> 参加者
参加者 -d-> 支払区分
参加者一覧 -d-> 支払重み合計値

支払区分 -d-> 支払重み

/'
支払計算 -d-> 支払一覧
支払計算 -d-> 参加者一覧
支払計算 -d-> 請求金額
支払計算 -d-> 重み毎支払金額
支払計算 -d-> 参加者毎支払金額
'/

支払一覧 -u-> 参加者一覧
支払一覧 -d-> 支払
支払一覧 -u-> 請求金額
支払一覧 -> 重み毎支払金額

支払 -d-> 参加者
支払 -d-> 参加者毎支払金額
支払 -> 重み毎支払金額

重み毎支払金額 -u-> 支払重み合計値
重み毎支払金額 -u-> 請求金額
重み毎支払金額 -d-> 金額


参加者毎支払金額 -d-> 金額
請求金額 -d-> 金額
@enduml
